services:
  rabbitmq:
    image: cyrilix/rabbitmq-mqtt
    ports:
      - "5672:5672"   # AMQP protocol
      - "15672:15672" # Management interface (fixed the port mapping)
      - "1883:1883"   # MQTT protocol
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 3
    restart: unless-stopped

  nuclio-dashboard:
    image: quay.io/nuclio/dashboard:stable-amd64
    ports:
      - "8070:8070"
    environment:
      - NUCLIO_DASHBOARD_EXTERNAL_IP_ADDRESSES=host.docker.internal
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - rabbitmq
    restart: unless-stopped

  f1-producer:
    build: .
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
      - CHECK_INTERVAL=${CHECK_INTERVAL:-90}
      - TEST_MODE=${TEST_MODE:-False}
      - TEST_YEAR=${TEST_YEAR:-2024}
      - TEST_RACE=${TEST_RACE:-Italian}
      - SIMULATE_LIVE=${SIMULATE_LIVE:-True}
      - CURRENT_LAP=${CURRENT_LAP:-1}
      - RABBITMQ_HOST=rabbitmq  # Adding this environment variable
    depends_on:
      rabbitmq:
        condition: service_healthy
    restart: unless-stopped

networks:
  default:
    name: nuclio-network
    driver: bridge